### PR TITLE
Initial setup for bahmni appointments on AMRS docker

### PR DESCRIPTION
**Pull request by drizzentic**
The setup will allow users to set up appointment types and create slots using the bahmni ui.

### CODE REVIEW

**Review by nkimaina — COMMENTED** [review]
How are the config files and the html files loaded into the app? Are you able to modify the Dockerfile to copy them over, because we are the only consumers of this docker image?

**Comment by nkimaina** [comment]
Also, make the PR against spa branch?

**Comment by drizzentic** [comment]
> How are the config files and the html files loaded into the app? Are you able to modify the Dockerfile to copy them over, because we are the only consumers of this docker image?

The `.first_run.sh` scripts copy the files and downloads the latest appointment frontend from the openmrs repos.

**Comment by drizzentic** [comment]
> Also, make the PR against spa branch?

@nkimaina I have done this and it looks like it will also bring changes from test-amrs branch because that's where i checked out from.

**Pull request closed without merging**
